/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import java.util.*;
import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AArray extends PArray
{
    private TIdentifier _identifier_;
    private final LinkedList<PArrayPosition> _arrayPosition_ = new LinkedList<PArrayPosition>();

    public AArray()
    {
        // Constructor
    }

    public AArray(
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") List<?> _arrayPosition_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setArrayPosition(_arrayPosition_);

    }

    @Override
    public Object clone()
    {
        return new AArray(
            cloneNode(this._identifier_),
            cloneList(this._arrayPosition_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArray(this);
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public LinkedList<PArrayPosition> getArrayPosition()
    {
        return this._arrayPosition_;
    }

    public void setArrayPosition(List<?> list)
    {
        for(PArrayPosition e : this._arrayPosition_)
        {
            e.parent(null);
        }
        this._arrayPosition_.clear();

        for(Object obj_e : list)
        {
            PArrayPosition e = (PArrayPosition) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._arrayPosition_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._arrayPosition_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._arrayPosition_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        for(ListIterator<PArrayPosition> i = this._arrayPosition_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PArrayPosition) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
