/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AArraySize extends PArraySize
{
    private TLbracket _lbracket_;
    private TIntConst _intConst_;
    private TRbracket _rbracket_;

    public AArraySize()
    {
        // Constructor
    }

    public AArraySize(
        @SuppressWarnings("hiding") TLbracket _lbracket_,
        @SuppressWarnings("hiding") TIntConst _intConst_,
        @SuppressWarnings("hiding") TRbracket _rbracket_)
    {
        // Constructor
        setLbracket(_lbracket_);

        setIntConst(_intConst_);

        setRbracket(_rbracket_);

    }

    @Override
    public Object clone()
    {
        return new AArraySize(
            cloneNode(this._lbracket_),
            cloneNode(this._intConst_),
            cloneNode(this._rbracket_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArraySize(this);
    }

    public TLbracket getLbracket()
    {
        return this._lbracket_;
    }

    public void setLbracket(TLbracket node)
    {
        if(this._lbracket_ != null)
        {
            this._lbracket_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lbracket_ = node;
    }

    public TIntConst getIntConst()
    {
        return this._intConst_;
    }

    public void setIntConst(TIntConst node)
    {
        if(this._intConst_ != null)
        {
            this._intConst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._intConst_ = node;
    }

    public TRbracket getRbracket()
    {
        return this._rbracket_;
    }

    public void setRbracket(TRbracket node)
    {
        if(this._rbracket_ != null)
        {
            this._rbracket_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rbracket_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lbracket_)
            + toString(this._intConst_)
            + toString(this._rbracket_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lbracket_ == child)
        {
            this._lbracket_ = null;
            return;
        }

        if(this._intConst_ == child)
        {
            this._intConst_ = null;
            return;
        }

        if(this._rbracket_ == child)
        {
            this._rbracket_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lbracket_ == oldChild)
        {
            setLbracket((TLbracket) newChild);
            return;
        }

        if(this._intConst_ == oldChild)
        {
            setIntConst((TIntConst) newChild);
            return;
        }

        if(this._rbracket_ == oldChild)
        {
            setRbracket((TRbracket) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
