/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ACompFinalCompVal extends PCompVal
{
    private PCompFinal _compFinal_;

    public ACompFinalCompVal()
    {
        // Constructor
    }

    public ACompFinalCompVal(
        @SuppressWarnings("hiding") PCompFinal _compFinal_)
    {
        // Constructor
        setCompFinal(_compFinal_);

    }

    @Override
    public Object clone()
    {
        return new ACompFinalCompVal(
            cloneNode(this._compFinal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACompFinalCompVal(this);
    }

    public PCompFinal getCompFinal()
    {
        return this._compFinal_;
    }

    public void setCompFinal(PCompFinal node)
    {
        if(this._compFinal_ != null)
        {
            this._compFinal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._compFinal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._compFinal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._compFinal_ == child)
        {
            this._compFinal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._compFinal_ == oldChild)
        {
            setCompFinal((PCompFinal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
