/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AEqualsCompVal extends PCompVal
{
    private PCompVal _compVal_;
    private TEquals _equals_;
    private PCompFinal _compFinal_;

    public AEqualsCompVal()
    {
        // Constructor
    }

    public AEqualsCompVal(
        @SuppressWarnings("hiding") PCompVal _compVal_,
        @SuppressWarnings("hiding") TEquals _equals_,
        @SuppressWarnings("hiding") PCompFinal _compFinal_)
    {
        // Constructor
        setCompVal(_compVal_);

        setEquals(_equals_);

        setCompFinal(_compFinal_);

    }

    @Override
    public Object clone()
    {
        return new AEqualsCompVal(
            cloneNode(this._compVal_),
            cloneNode(this._equals_),
            cloneNode(this._compFinal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqualsCompVal(this);
    }

    public PCompVal getCompVal()
    {
        return this._compVal_;
    }

    public void setCompVal(PCompVal node)
    {
        if(this._compVal_ != null)
        {
            this._compVal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._compVal_ = node;
    }

    public TEquals getEquals()
    {
        return this._equals_;
    }

    public void setEquals(TEquals node)
    {
        if(this._equals_ != null)
        {
            this._equals_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equals_ = node;
    }

    public PCompFinal getCompFinal()
    {
        return this._compFinal_;
    }

    public void setCompFinal(PCompFinal node)
    {
        if(this._compFinal_ != null)
        {
            this._compFinal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._compFinal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._compVal_)
            + toString(this._equals_)
            + toString(this._compFinal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._compVal_ == child)
        {
            this._compVal_ = null;
            return;
        }

        if(this._equals_ == child)
        {
            this._equals_ = null;
            return;
        }

        if(this._compFinal_ == child)
        {
            this._compFinal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._compVal_ == oldChild)
        {
            setCompVal((PCompVal) newChild);
            return;
        }

        if(this._equals_ == oldChild)
        {
            setEquals((TEquals) newChild);
            return;
        }

        if(this._compFinal_ == oldChild)
        {
            setCompFinal((PCompFinal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
