/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AExponentTerm extends PTerm
{
    private PExponent _exponent_;

    public AExponentTerm()
    {
        // Constructor
    }

    public AExponentTerm(
        @SuppressWarnings("hiding") PExponent _exponent_)
    {
        // Constructor
        setExponent(_exponent_);

    }

    @Override
    public Object clone()
    {
        return new AExponentTerm(
            cloneNode(this._exponent_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExponentTerm(this);
    }

    public PExponent getExponent()
    {
        return this._exponent_;
    }

    public void setExponent(PExponent node)
    {
        if(this._exponent_ != null)
        {
            this._exponent_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exponent_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exponent_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exponent_ == child)
        {
            this._exponent_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exponent_ == oldChild)
        {
            setExponent((PExponent) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
