/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import java.util.*;
import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AFparDefinition extends PFparDefinition
{
    private TKwRef _kwRef_;
    private TIdentifier _identifier_;
    private final LinkedList<PNextIdentifier> _nextIdentifier_ = new LinkedList<PNextIdentifier>();
    private TColon _colon_;
    private PFparType _fparType_;

    public AFparDefinition()
    {
        // Constructor
    }

    public AFparDefinition(
        @SuppressWarnings("hiding") TKwRef _kwRef_,
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") List<?> _nextIdentifier_,
        @SuppressWarnings("hiding") TColon _colon_,
        @SuppressWarnings("hiding") PFparType _fparType_)
    {
        // Constructor
        setKwRef(_kwRef_);

        setIdentifier(_identifier_);

        setNextIdentifier(_nextIdentifier_);

        setColon(_colon_);

        setFparType(_fparType_);

    }

    @Override
    public Object clone()
    {
        return new AFparDefinition(
            cloneNode(this._kwRef_),
            cloneNode(this._identifier_),
            cloneList(this._nextIdentifier_),
            cloneNode(this._colon_),
            cloneNode(this._fparType_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFparDefinition(this);
    }

    public TKwRef getKwRef()
    {
        return this._kwRef_;
    }

    public void setKwRef(TKwRef node)
    {
        if(this._kwRef_ != null)
        {
            this._kwRef_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwRef_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public LinkedList<PNextIdentifier> getNextIdentifier()
    {
        return this._nextIdentifier_;
    }

    public void setNextIdentifier(List<?> list)
    {
        for(PNextIdentifier e : this._nextIdentifier_)
        {
            e.parent(null);
        }
        this._nextIdentifier_.clear();

        for(Object obj_e : list)
        {
            PNextIdentifier e = (PNextIdentifier) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._nextIdentifier_.add(e);
        }
    }

    public TColon getColon()
    {
        return this._colon_;
    }

    public void setColon(TColon node)
    {
        if(this._colon_ != null)
        {
            this._colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colon_ = node;
    }

    public PFparType getFparType()
    {
        return this._fparType_;
    }

    public void setFparType(PFparType node)
    {
        if(this._fparType_ != null)
        {
            this._fparType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fparType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwRef_)
            + toString(this._identifier_)
            + toString(this._nextIdentifier_)
            + toString(this._colon_)
            + toString(this._fparType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwRef_ == child)
        {
            this._kwRef_ = null;
            return;
        }

        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._nextIdentifier_.remove(child))
        {
            return;
        }

        if(this._colon_ == child)
        {
            this._colon_ = null;
            return;
        }

        if(this._fparType_ == child)
        {
            this._fparType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwRef_ == oldChild)
        {
            setKwRef((TKwRef) newChild);
            return;
        }

        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        for(ListIterator<PNextIdentifier> i = this._nextIdentifier_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PNextIdentifier) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        if(this._fparType_ == oldChild)
        {
            setFparType((PFparType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
