/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import java.util.*;
import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AFunctionDefinitionFunctionDefinition extends PFunctionDefinition
{
    private PHeader _header_;
    private final LinkedList<PLocalDefinition> _localDefinition_ = new LinkedList<PLocalDefinition>();
    private PStatement _statement_;

    public AFunctionDefinitionFunctionDefinition()
    {
        // Constructor
    }

    public AFunctionDefinitionFunctionDefinition(
        @SuppressWarnings("hiding") PHeader _header_,
        @SuppressWarnings("hiding") List<?> _localDefinition_,
        @SuppressWarnings("hiding") PStatement _statement_)
    {
        // Constructor
        setHeader(_header_);

        setLocalDefinition(_localDefinition_);

        setStatement(_statement_);

    }

    @Override
    public Object clone()
    {
        return new AFunctionDefinitionFunctionDefinition(
            cloneNode(this._header_),
            cloneList(this._localDefinition_),
            cloneNode(this._statement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunctionDefinitionFunctionDefinition(this);
    }

    public PHeader getHeader()
    {
        return this._header_;
    }

    public void setHeader(PHeader node)
    {
        if(this._header_ != null)
        {
            this._header_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._header_ = node;
    }

    public LinkedList<PLocalDefinition> getLocalDefinition()
    {
        return this._localDefinition_;
    }

    public void setLocalDefinition(List<?> list)
    {
        for(PLocalDefinition e : this._localDefinition_)
        {
            e.parent(null);
        }
        this._localDefinition_.clear();

        for(Object obj_e : list)
        {
            PLocalDefinition e = (PLocalDefinition) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._localDefinition_.add(e);
        }
    }

    public PStatement getStatement()
    {
        return this._statement_;
    }

    public void setStatement(PStatement node)
    {
        if(this._statement_ != null)
        {
            this._statement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._statement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._header_)
            + toString(this._localDefinition_)
            + toString(this._statement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._header_ == child)
        {
            this._header_ = null;
            return;
        }

        if(this._localDefinition_.remove(child))
        {
            return;
        }

        if(this._statement_ == child)
        {
            this._statement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._header_ == oldChild)
        {
            setHeader((PHeader) newChild);
            return;
        }

        for(ListIterator<PLocalDefinition> i = this._localDefinition_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PLocalDefinition) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._statement_ == oldChild)
        {
            setStatement((PStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
