/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AFunctionDeclarationHeaderFunctionDeclaration extends PFunctionDeclaration
{
    private PHeader _header_;

    public AFunctionDeclarationHeaderFunctionDeclaration()
    {
        // Constructor
    }

    public AFunctionDeclarationHeaderFunctionDeclaration(
        @SuppressWarnings("hiding") PHeader _header_)
    {
        // Constructor
        setHeader(_header_);

    }

    @Override
    public Object clone()
    {
        return new AFunctionDeclarationHeaderFunctionDeclaration(
            cloneNode(this._header_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunctionDeclarationHeaderFunctionDeclaration(this);
    }

    public PHeader getHeader()
    {
        return this._header_;
    }

    public void setHeader(PHeader node)
    {
        if(this._header_ != null)
        {
            this._header_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._header_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._header_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._header_ == child)
        {
            this._header_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._header_ == oldChild)
        {
            setHeader((PHeader) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
