/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AGreaterOrEqualCompVal extends PCompVal
{
    private PCompVal _compVal_;
    private TGreaterThanEqual _greaterThanEqual_;
    private PCompFinal _compFinal_;

    public AGreaterOrEqualCompVal()
    {
        // Constructor
    }

    public AGreaterOrEqualCompVal(
        @SuppressWarnings("hiding") PCompVal _compVal_,
        @SuppressWarnings("hiding") TGreaterThanEqual _greaterThanEqual_,
        @SuppressWarnings("hiding") PCompFinal _compFinal_)
    {
        // Constructor
        setCompVal(_compVal_);

        setGreaterThanEqual(_greaterThanEqual_);

        setCompFinal(_compFinal_);

    }

    @Override
    public Object clone()
    {
        return new AGreaterOrEqualCompVal(
            cloneNode(this._compVal_),
            cloneNode(this._greaterThanEqual_),
            cloneNode(this._compFinal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGreaterOrEqualCompVal(this);
    }

    public PCompVal getCompVal()
    {
        return this._compVal_;
    }

    public void setCompVal(PCompVal node)
    {
        if(this._compVal_ != null)
        {
            this._compVal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._compVal_ = node;
    }

    public TGreaterThanEqual getGreaterThanEqual()
    {
        return this._greaterThanEqual_;
    }

    public void setGreaterThanEqual(TGreaterThanEqual node)
    {
        if(this._greaterThanEqual_ != null)
        {
            this._greaterThanEqual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._greaterThanEqual_ = node;
    }

    public PCompFinal getCompFinal()
    {
        return this._compFinal_;
    }

    public void setCompFinal(PCompFinal node)
    {
        if(this._compFinal_ != null)
        {
            this._compFinal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._compFinal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._compVal_)
            + toString(this._greaterThanEqual_)
            + toString(this._compFinal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._compVal_ == child)
        {
            this._compVal_ = null;
            return;
        }

        if(this._greaterThanEqual_ == child)
        {
            this._greaterThanEqual_ = null;
            return;
        }

        if(this._compFinal_ == child)
        {
            this._compFinal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._compVal_ == oldChild)
        {
            setCompVal((PCompVal) newChild);
            return;
        }

        if(this._greaterThanEqual_ == oldChild)
        {
            setGreaterThanEqual((TGreaterThanEqual) newChild);
            return;
        }

        if(this._compFinal_ == oldChild)
        {
            setCompFinal((PCompFinal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
