/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AGreaterOrEqualComparisonSymbols extends PComparisonSymbols
{
    private TGreaterThanEqual _greaterThanEqual_;

    public AGreaterOrEqualComparisonSymbols()
    {
        // Constructor
    }

    public AGreaterOrEqualComparisonSymbols(
        @SuppressWarnings("hiding") TGreaterThanEqual _greaterThanEqual_)
    {
        // Constructor
        setGreaterThanEqual(_greaterThanEqual_);

    }

    @Override
    public Object clone()
    {
        return new AGreaterOrEqualComparisonSymbols(
            cloneNode(this._greaterThanEqual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGreaterOrEqualComparisonSymbols(this);
    }

    public TGreaterThanEqual getGreaterThanEqual()
    {
        return this._greaterThanEqual_;
    }

    public void setGreaterThanEqual(TGreaterThanEqual node)
    {
        if(this._greaterThanEqual_ != null)
        {
            this._greaterThanEqual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._greaterThanEqual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._greaterThanEqual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._greaterThanEqual_ == child)
        {
            this._greaterThanEqual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._greaterThanEqual_ == oldChild)
        {
            setGreaterThanEqual((TGreaterThanEqual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
