/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import java.util.*;
import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AHeaderHeader extends PHeader
{
    private TIdentifier _identifier_;
    private PFparDefinition _fparDefinition_;
    private final LinkedList<PNextFparDefinition> _nextFparDefinition_ = new LinkedList<PNextFparDefinition>();
    private PRetType _retType_;

    public AHeaderHeader()
    {
        // Constructor
    }

    public AHeaderHeader(
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") PFparDefinition _fparDefinition_,
        @SuppressWarnings("hiding") List<?> _nextFparDefinition_,
        @SuppressWarnings("hiding") PRetType _retType_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setFparDefinition(_fparDefinition_);

        setNextFparDefinition(_nextFparDefinition_);

        setRetType(_retType_);

    }

    @Override
    public Object clone()
    {
        return new AHeaderHeader(
            cloneNode(this._identifier_),
            cloneNode(this._fparDefinition_),
            cloneList(this._nextFparDefinition_),
            cloneNode(this._retType_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHeaderHeader(this);
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public PFparDefinition getFparDefinition()
    {
        return this._fparDefinition_;
    }

    public void setFparDefinition(PFparDefinition node)
    {
        if(this._fparDefinition_ != null)
        {
            this._fparDefinition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fparDefinition_ = node;
    }

    public LinkedList<PNextFparDefinition> getNextFparDefinition()
    {
        return this._nextFparDefinition_;
    }

    public void setNextFparDefinition(List<?> list)
    {
        for(PNextFparDefinition e : this._nextFparDefinition_)
        {
            e.parent(null);
        }
        this._nextFparDefinition_.clear();

        for(Object obj_e : list)
        {
            PNextFparDefinition e = (PNextFparDefinition) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._nextFparDefinition_.add(e);
        }
    }

    public PRetType getRetType()
    {
        return this._retType_;
    }

    public void setRetType(PRetType node)
    {
        if(this._retType_ != null)
        {
            this._retType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._retType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._fparDefinition_)
            + toString(this._nextFparDefinition_)
            + toString(this._retType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._fparDefinition_ == child)
        {
            this._fparDefinition_ = null;
            return;
        }

        if(this._nextFparDefinition_.remove(child))
        {
            return;
        }

        if(this._retType_ == child)
        {
            this._retType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(this._fparDefinition_ == oldChild)
        {
            setFparDefinition((PFparDefinition) newChild);
            return;
        }

        for(ListIterator<PNextFparDefinition> i = this._nextFparDefinition_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PNextFparDefinition) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._retType_ == oldChild)
        {
            setRetType((PRetType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
