/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ALogicOperationCondition extends PCondition
{
    private PCondition _first_;
    private PLogicOperations _logicOperations_;
    private PCondition _second_;

    public ALogicOperationCondition()
    {
        // Constructor
    }

    public ALogicOperationCondition(
        @SuppressWarnings("hiding") PCondition _first_,
        @SuppressWarnings("hiding") PLogicOperations _logicOperations_,
        @SuppressWarnings("hiding") PCondition _second_)
    {
        // Constructor
        setFirst(_first_);

        setLogicOperations(_logicOperations_);

        setSecond(_second_);

    }

    @Override
    public Object clone()
    {
        return new ALogicOperationCondition(
            cloneNode(this._first_),
            cloneNode(this._logicOperations_),
            cloneNode(this._second_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALogicOperationCondition(this);
    }

    public PCondition getFirst()
    {
        return this._first_;
    }

    public void setFirst(PCondition node)
    {
        if(this._first_ != null)
        {
            this._first_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._first_ = node;
    }

    public PLogicOperations getLogicOperations()
    {
        return this._logicOperations_;
    }

    public void setLogicOperations(PLogicOperations node)
    {
        if(this._logicOperations_ != null)
        {
            this._logicOperations_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logicOperations_ = node;
    }

    public PCondition getSecond()
    {
        return this._second_;
    }

    public void setSecond(PCondition node)
    {
        if(this._second_ != null)
        {
            this._second_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._second_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._first_)
            + toString(this._logicOperations_)
            + toString(this._second_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._first_ == child)
        {
            this._first_ = null;
            return;
        }

        if(this._logicOperations_ == child)
        {
            this._logicOperations_ = null;
            return;
        }

        if(this._second_ == child)
        {
            this._second_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._first_ == oldChild)
        {
            setFirst((PCondition) newChild);
            return;
        }

        if(this._logicOperations_ == oldChild)
        {
            setLogicOperations((PLogicOperations) newChild);
            return;
        }

        if(this._second_ == oldChild)
        {
            setSecond((PCondition) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
