/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AMatchedIfStmt extends PIfStmt
{
    private PMatched _matched_;

    public AMatchedIfStmt()
    {
        // Constructor
    }

    public AMatchedIfStmt(
        @SuppressWarnings("hiding") PMatched _matched_)
    {
        // Constructor
        setMatched(_matched_);

    }

    @Override
    public Object clone()
    {
        return new AMatchedIfStmt(
            cloneNode(this._matched_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMatchedIfStmt(this);
    }

    public PMatched getMatched()
    {
        return this._matched_;
    }

    public void setMatched(PMatched node)
    {
        if(this._matched_ != null)
        {
            this._matched_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._matched_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._matched_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._matched_ == child)
        {
            this._matched_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._matched_ == oldChild)
        {
            setMatched((PMatched) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
