/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AModNumOperations extends PNumOperations
{
    private TKwMod _kwMod_;

    public AModNumOperations()
    {
        // Constructor
    }

    public AModNumOperations(
        @SuppressWarnings("hiding") TKwMod _kwMod_)
    {
        // Constructor
        setKwMod(_kwMod_);

    }

    @Override
    public Object clone()
    {
        return new AModNumOperations(
            cloneNode(this._kwMod_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAModNumOperations(this);
    }

    public TKwMod getKwMod()
    {
        return this._kwMod_;
    }

    public void setKwMod(TKwMod node)
    {
        if(this._kwMod_ != null)
        {
            this._kwMod_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwMod_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwMod_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwMod_ == child)
        {
            this._kwMod_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwMod_ == oldChild)
        {
            setKwMod((TKwMod) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
