/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import java.util.*;
import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AMultipleExpressions extends PMultipleExpressions
{
    private PExpression _expression_;
    private final LinkedList<PNextExpression> _nextExpression_ = new LinkedList<PNextExpression>();

    public AMultipleExpressions()
    {
        // Constructor
    }

    public AMultipleExpressions(
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") List<?> _nextExpression_)
    {
        // Constructor
        setExpression(_expression_);

        setNextExpression(_nextExpression_);

    }

    @Override
    public Object clone()
    {
        return new AMultipleExpressions(
            cloneNode(this._expression_),
            cloneList(this._nextExpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultipleExpressions(this);
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public LinkedList<PNextExpression> getNextExpression()
    {
        return this._nextExpression_;
    }

    public void setNextExpression(List<?> list)
    {
        for(PNextExpression e : this._nextExpression_)
        {
            e.parent(null);
        }
        this._nextExpression_.clear();

        for(Object obj_e : list)
        {
            PNextExpression e = (PNextExpression) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._nextExpression_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expression_)
            + toString(this._nextExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._nextExpression_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        for(ListIterator<PNextExpression> i = this._nextExpression_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PNextExpression) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
