/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ANextFparDefinition extends PNextFparDefinition
{
    private TSemicolon _semicolon_;
    private PFparDefinition _fparDefinition_;

    public ANextFparDefinition()
    {
        // Constructor
    }

    public ANextFparDefinition(
        @SuppressWarnings("hiding") TSemicolon _semicolon_,
        @SuppressWarnings("hiding") PFparDefinition _fparDefinition_)
    {
        // Constructor
        setSemicolon(_semicolon_);

        setFparDefinition(_fparDefinition_);

    }

    @Override
    public Object clone()
    {
        return new ANextFparDefinition(
            cloneNode(this._semicolon_),
            cloneNode(this._fparDefinition_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANextFparDefinition(this);
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    public PFparDefinition getFparDefinition()
    {
        return this._fparDefinition_;
    }

    public void setFparDefinition(PFparDefinition node)
    {
        if(this._fparDefinition_ != null)
        {
            this._fparDefinition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fparDefinition_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._semicolon_)
            + toString(this._fparDefinition_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        if(this._fparDefinition_ == child)
        {
            this._fparDefinition_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        if(this._fparDefinition_ == oldChild)
        {
            setFparDefinition((PFparDefinition) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
