/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ANoAndExpCompTerm extends PCompTerm
{
    private PCompFun _compFun_;

    public ANoAndExpCompTerm()
    {
        // Constructor
    }

    public ANoAndExpCompTerm(
        @SuppressWarnings("hiding") PCompFun _compFun_)
    {
        // Constructor
        setCompFun(_compFun_);

    }

    @Override
    public Object clone()
    {
        return new ANoAndExpCompTerm(
            cloneNode(this._compFun_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANoAndExpCompTerm(this);
    }

    public PCompFun getCompFun()
    {
        return this._compFun_;
    }

    public void setCompFun(PCompFun node)
    {
        if(this._compFun_ != null)
        {
            this._compFun_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._compFun_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._compFun_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._compFun_ == child)
        {
            this._compFun_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._compFun_ == oldChild)
        {
            setCompFun((PCompFun) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
