/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ANoNotExpCompFun extends PCompFun
{
    private PCompVal _compVal_;

    public ANoNotExpCompFun()
    {
        // Constructor
    }

    public ANoNotExpCompFun(
        @SuppressWarnings("hiding") PCompVal _compVal_)
    {
        // Constructor
        setCompVal(_compVal_);

    }

    @Override
    public Object clone()
    {
        return new ANoNotExpCompFun(
            cloneNode(this._compVal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANoNotExpCompFun(this);
    }

    public PCompVal getCompVal()
    {
        return this._compVal_;
    }

    public void setCompVal(PCompVal node)
    {
        if(this._compVal_ != null)
        {
            this._compVal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._compVal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._compVal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._compVal_ == child)
        {
            this._compVal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._compVal_ == oldChild)
        {
            setCompVal((PCompVal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
