/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ANoOrExpCompExp extends PCompExp
{
    private PCompTerm _compTerm_;

    public ANoOrExpCompExp()
    {
        // Constructor
    }

    public ANoOrExpCompExp(
        @SuppressWarnings("hiding") PCompTerm _compTerm_)
    {
        // Constructor
        setCompTerm(_compTerm_);

    }

    @Override
    public Object clone()
    {
        return new ANoOrExpCompExp(
            cloneNode(this._compTerm_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANoOrExpCompExp(this);
    }

    public PCompTerm getCompTerm()
    {
        return this._compTerm_;
    }

    public void setCompTerm(PCompTerm node)
    {
        if(this._compTerm_ != null)
        {
            this._compTerm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._compTerm_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._compTerm_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._compTerm_ == child)
        {
            this._compTerm_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._compTerm_ == oldChild)
        {
            setCompTerm((PCompTerm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
