/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ANotExpCompFun extends PCompFun
{
    private TKwNot _kwNot_;
    private PCompFun _compFun_;

    public ANotExpCompFun()
    {
        // Constructor
    }

    public ANotExpCompFun(
        @SuppressWarnings("hiding") TKwNot _kwNot_,
        @SuppressWarnings("hiding") PCompFun _compFun_)
    {
        // Constructor
        setKwNot(_kwNot_);

        setCompFun(_compFun_);

    }

    @Override
    public Object clone()
    {
        return new ANotExpCompFun(
            cloneNode(this._kwNot_),
            cloneNode(this._compFun_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotExpCompFun(this);
    }

    public TKwNot getKwNot()
    {
        return this._kwNot_;
    }

    public void setKwNot(TKwNot node)
    {
        if(this._kwNot_ != null)
        {
            this._kwNot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwNot_ = node;
    }

    public PCompFun getCompFun()
    {
        return this._compFun_;
    }

    public void setCompFun(PCompFun node)
    {
        if(this._compFun_ != null)
        {
            this._compFun_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._compFun_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwNot_)
            + toString(this._compFun_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwNot_ == child)
        {
            this._kwNot_ = null;
            return;
        }

        if(this._compFun_ == child)
        {
            this._compFun_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwNot_ == oldChild)
        {
            setKwNot((TKwNot) newChild);
            return;
        }

        if(this._compFun_ == oldChild)
        {
            setCompFun((PCompFun) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
