/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ANotExpCompExp extends PCompExp
{
    private PCompExp _compExp_;

    public ANotExpCompExp()
    {
        // Constructor
    }

    public ANotExpCompExp(
        @SuppressWarnings("hiding") PCompExp _compExp_)
    {
        // Constructor
        setCompExp(_compExp_);

    }

    @Override
    public Object clone()
    {
        return new ANotExpCompExp(
            cloneNode(this._compExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotExpCompExp(this);
    }

    public PCompExp getCompExp()
    {
        return this._compExp_;
    }

    public void setCompExp(PCompExp node)
    {
        if(this._compExp_ != null)
        {
            this._compExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._compExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._compExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._compExp_ == child)
        {
            this._compExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._compExp_ == oldChild)
        {
            setCompExp((PCompExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
