/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ANumOperExpression extends PExpression
{
    private PNExp _nExp_;

    public ANumOperExpression()
    {
        // Constructor
    }

    public ANumOperExpression(
        @SuppressWarnings("hiding") PNExp _nExp_)
    {
        // Constructor
        setNExp(_nExp_);

    }

    @Override
    public Object clone()
    {
        return new ANumOperExpression(
            cloneNode(this._nExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumOperExpression(this);
    }

    public PNExp getNExp()
    {
        return this._nExp_;
    }

    public void setNExp(PNExp node)
    {
        if(this._nExp_ != null)
        {
            this._nExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nExp_ == child)
        {
            this._nExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nExp_ == oldChild)
        {
            setNExp((PNExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
