/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AOrLogicOperations extends PLogicOperations
{
    private TKwOr _kwOr_;

    public AOrLogicOperations()
    {
        // Constructor
    }

    public AOrLogicOperations(
        @SuppressWarnings("hiding") TKwOr _kwOr_)
    {
        // Constructor
        setKwOr(_kwOr_);

    }

    @Override
    public Object clone()
    {
        return new AOrLogicOperations(
            cloneNode(this._kwOr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrLogicOperations(this);
    }

    public TKwOr getKwOr()
    {
        return this._kwOr_;
    }

    public void setKwOr(TKwOr node)
    {
        if(this._kwOr_ != null)
        {
            this._kwOr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwOr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwOr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwOr_ == child)
        {
            this._kwOr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwOr_ == oldChild)
        {
            setKwOr((TKwOr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
