/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ATermMultTerm extends PTerm
{
    private PTerm _term_;
    private TMult _mult_;
    private PExponent _exponent_;

    public ATermMultTerm()
    {
        // Constructor
    }

    public ATermMultTerm(
        @SuppressWarnings("hiding") PTerm _term_,
        @SuppressWarnings("hiding") TMult _mult_,
        @SuppressWarnings("hiding") PExponent _exponent_)
    {
        // Constructor
        setTerm(_term_);

        setMult(_mult_);

        setExponent(_exponent_);

    }

    @Override
    public Object clone()
    {
        return new ATermMultTerm(
            cloneNode(this._term_),
            cloneNode(this._mult_),
            cloneNode(this._exponent_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATermMultTerm(this);
    }

    public PTerm getTerm()
    {
        return this._term_;
    }

    public void setTerm(PTerm node)
    {
        if(this._term_ != null)
        {
            this._term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._term_ = node;
    }

    public TMult getMult()
    {
        return this._mult_;
    }

    public void setMult(TMult node)
    {
        if(this._mult_ != null)
        {
            this._mult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mult_ = node;
    }

    public PExponent getExponent()
    {
        return this._exponent_;
    }

    public void setExponent(PExponent node)
    {
        if(this._exponent_ != null)
        {
            this._exponent_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exponent_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._term_)
            + toString(this._mult_)
            + toString(this._exponent_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._term_ == child)
        {
            this._term_ = null;
            return;
        }

        if(this._mult_ == child)
        {
            this._mult_ = null;
            return;
        }

        if(this._exponent_ == child)
        {
            this._exponent_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

        if(this._mult_ == oldChild)
        {
            setMult((TMult) newChild);
            return;
        }

        if(this._exponent_ == oldChild)
        {
            setExponent((PExponent) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
