/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AVarDefLocalDefinition extends PLocalDefinition
{
    private PVarDefinition _varDefinition_;

    public AVarDefLocalDefinition()
    {
        // Constructor
    }

    public AVarDefLocalDefinition(
        @SuppressWarnings("hiding") PVarDefinition _varDefinition_)
    {
        // Constructor
        setVarDefinition(_varDefinition_);

    }

    @Override
    public Object clone()
    {
        return new AVarDefLocalDefinition(
            cloneNode(this._varDefinition_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarDefLocalDefinition(this);
    }

    public PVarDefinition getVarDefinition()
    {
        return this._varDefinition_;
    }

    public void setVarDefinition(PVarDefinition node)
    {
        if(this._varDefinition_ != null)
        {
            this._varDefinition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varDefinition_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varDefinition_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varDefinition_ == child)
        {
            this._varDefinition_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varDefinition_ == oldChild)
        {
            setVarDefinition((PVarDefinition) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
