/* This file was generated by SableCC (http://www.sablecc.org/). */

package sablecc.node;

import sablecc.analysis.*;

@SuppressWarnings("nls")
public final class Start extends Node
{
    private PFunctionDefinition _pFunctionDefinition_;
    private EOF _eof_;

    public Start()
    {
        // Empty body
    }

    public Start(
        @SuppressWarnings("hiding") PFunctionDefinition _pFunctionDefinition_,
        @SuppressWarnings("hiding") EOF _eof_)
    {
        setPFunctionDefinition(_pFunctionDefinition_);
        setEOF(_eof_);
    }

    @Override
    public Object clone()
    {
        return new Start(
            cloneNode(this._pFunctionDefinition_),
            cloneNode(this._eof_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseStart(this);
    }

    public PFunctionDefinition getPFunctionDefinition()
    {
        return this._pFunctionDefinition_;
    }

    public void setPFunctionDefinition(PFunctionDefinition node)
    {
        if(this._pFunctionDefinition_ != null)
        {
            this._pFunctionDefinition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pFunctionDefinition_ = node;
    }

    public EOF getEOF()
    {
        return this._eof_;
    }

    public void setEOF(EOF node)
    {
        if(this._eof_ != null)
        {
            this._eof_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eof_ = node;
    }

    @Override
    void removeChild(Node child)
    {
        if(this._pFunctionDefinition_ == child)
        {
            this._pFunctionDefinition_ = null;
            return;
        }

        if(this._eof_ == child)
        {
            this._eof_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(Node oldChild, Node newChild)
    {
        if(this._pFunctionDefinition_ == oldChild)
        {
            setPFunctionDefinition((PFunctionDefinition) newChild);
            return;
        }

        if(this._eof_ == oldChild)
        {
            setEOF((EOF) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    public String toString()
    {
        return "" +
            toString(this._pFunctionDefinition_) +
            toString(this._eof_);
    }
}
